#!/bin/sh

brew bundle --file=- <<EOF
cask "java"
cask "go-agent"
cask "google-chrome"
cask "appcleaner"
cask "movist"
cask "istat-menus"
cask "dropbox"

cask "electronic-wechat"
cask "slack"
cask "aliwangwang"

cask "iterm2"
brew "tmux"
brew "htop"
brew "wget"
brew "pyenv"
cask "pycharm"
cask "macvim"
cask "sequel-pro"
cask "charles"
brew "httpstat"

cask "sogouinput"
cask "alfred"
cask "spectacle"
cask "rescuetime"
cask "go2shell"
cask "qq"
cask "cheatsheet"
EOF

fancy_echo "Cleaning up old Homebrew formulae ..."
brew cleanup
brew cask cleanup

if [ -r "$HOME/.rcrc" ]; then
  fancy_echo "Updating dotfiles ..."
  rcup
fi
