#!/bin/sh

brew bundle --file=- <<EOF
brew "iterm2"
brew "istat-menus"
brew "google-chrome"
EOF

fancy_echo "Cleaning up old Homebrew formulae ..."
brew cleanup
brew cask cleanup

if [ -r "$HOME/.rcrc" ]; then
  fancy_echo "Updating dotfiles ..."
  rcup
fi
